Hip-tests-update
CHIP-SPV/chipStar pull request #796
Opened 2024-03-11 12:38 UTC by pvelesko

2024-03-21 06:49 UTC, linehill commented
> ```
> 863: CHIP warning [TID 3650729] [1710422994.385196816] : A device function is already registered and mapped to a different module.
> ```

Probably just a false positive. I wrote the warning at a time I didn’t fully understood what was happening (__hipRegisterFuntcion() called multiple times with same host pointer). I made a patch to remove it: https://github.com/CHIP-SPV/chipStar/pull/809.

2024-03-21 06:58 UTC, linehill commented
FYI, building this branch from scratch with multiple jobs may end up in a situation where hipcc is not built before building hip-tests:
```
...
cd /mnt/md1/linehill/ws-chipstar-2/builds/chipstar/catch/catch_tests/unit/module && ../../../../bin/hipcc --genco --std=c++17 /mnt/md1/linehill/ws-chipstar-2/chipstar/hip-tests/catch/unit/module/get_function_module.cc -o get_function_module.code -I/mnt/md1/linehill/ws-chipstar-2/builds/chipstar/include/ --rocm-path=/opt/rocm
/bin/sh: 1: ../../../../bin/hipcc: not found
catch/catch_tests/unit/module/CMakeFiles/get_function_module.dir/build.make:72: recipe for target 'catch/catch_tests/unit/module/get_function_module.code' failed
make[2]: *** [catch/catch_tests/unit/module/get_function_module.code] Error 127
...
```

2024-03-21 07:00 UTC, linehill commented
```
/mnt/md1/linehill/ws-chipstar-2/chipstar/include/hip/devicelib/type_casting_intrinsics.hh:32:36: warning: inline function '__double2hiint' is not defined [-Wundefined-inline]
extern "C++" inline __device__ int __double2hiint(double x);
```
Removing the `inline` suppresses the warning. The `inline` qualifier is only meaningful for function definitions.

2024-04-02 09:51 UTC, linehill requested changes
* Please run clang-format for the whole patch set. E.g. with `git clang-format main`.
* Did you check if there are new `hipDeviceProp_t` and `hipDeviceAttribute_t` entries and updated `hipGetDeviceProperties()` and `hipDeviceGetAttribute()` to respond to them?

2024-04-02 09:54 UTC, pvelesko commented on include/hip/spirv_hip_runtime.h
> +#define __managed__ __device__
without this we get undefined keyword so just added this as a placeholder to get everything to compile

2024-04-02 11:30 UTC, linehill commented on include/hip/spirv_hip_runtime.h
> +#define __managed__ __device__
Fair enough.

2024-04-02 21:39 UTC, pvelesko commented on include/hip/spirv_hip_cooperative_groups_helper.h
> +unsigned int __device__ __builtin_amdgcn_read_exec(void){return 0;};
None since we don't have an implementation. I added an entry

2024-04-03 07:48 UTC, linehill approved these changes
LGTM.

2024-04-04 07:54 UTC, merged